[project]
authors = ["Joren Dumoulin <joren.dumoulin@kuleuven.be>"]
channels = ["conda-forge"]
name = "mlir-networks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.tensorflow.dependencies]
tensorflow = "==2.16.2"
python = "==3.12"

[environments]
mlperf-tiny = ["tensorflow"]
