[project]
authors = ["Joren Dumoulin <joren.dumoulin@kuleuven.be>"]
channels = ["conda-forge"]
name = "mlir-networks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
opencv = ">=4.10.0,<5"

[feature.tensorflow.dependencies]
tensorflow = "==2.16.2"
python = "==3.12"
mlir = "==19.1.0"

[feature.test-mlir.dependencies]
mlir = "==20.1.1"

[feature.xdsl.pypi-dependencies]
xdsl = "==0.51.0"

[environments]
default = ["test-mlir"]
mlperf-tiny = ["tensorflow", "xdsl"]
ailia = ["tensorflow", "xdsl"]
test-mlir = ["test-mlir"]

[pypi-dependencies]
ailia-tflite = ">=1.2.2.0, <2"
