[project]
authors = ["Joren Dumoulin <joren.dumoulin@kuleuven.be>"]
channels = ["conda-forge"]
name = "mlir-networks"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]

[feature.tensorflow.dependencies]
tensorflow = "==2.16.2"
python = "==3.12"
mlir = "==19.1.0"

[feature.test-mlir.dependencies]
mlir = "==20.1.1"

[feature.xdsl.pypi-dependencies]
xdsl = "*"

[environments]
default = ["test-mlir"]
mlperf-tiny = ["tensorflow", "xdsl"]
test-mlir = ["test-mlir"]
